name: Przyklad Zmiennych Workflow  
on: workflow_dispatch  # ręczne uruchomienie dla testów

env:
  CLOUD: Azure  # zmienna globalna

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GREETING: "Cześć"    # zmienna dla joba "build"
    steps:
      - name: Przyklad zmiennych
        env:
          NAME: "Tobisof"    # zmienna tylko dla tego kroku
        run: |
            echo "$GREETING $NAME! ostatnio korzystasz z $CLOUD." 
            echo "Pokazanie naszej zmiennej ${{ vars.COURSE_NAME }}"
